### ISSUE TITLE
Fix GRUB_CMDLINE_LINUX_DEFAULT overwriting.

### ISSUE THREAD

**Issue by pocorall** [gantsign/ansible_role_zswap#10]
Some packages have configurations that overwrites `GRUB_CMDLINE_LINUX_DEFAULT` setting in `/etc/default/grub`.

https://bugs.launchpad.net/vmbuilder/+bug/1692471
https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1569567

vmbuilder did not fix this problem, and released with Ubuntu 20.04. Although it is not a bug of this project, I think it is better address this problem because the problem disables core functionality of this project. Possible solution is adding a new task:

```
    - name: Fix VMBuilder bug -- https://bugs.launchpad.net/vmbuilder/+bug/1692471 -- https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1569567
      lineinfile:
        path: '/etc/default/grub.d/50-cloudimg-settings.cfg'
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?!\$GRUB_CMDLINE_LINUX_DEFAULT).*)"'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT \1"'
        backrefs: yes
      notify:
        - update-grub
```
